
spring:
  application:
    name: BookBackend
  profiles:
    active: dev  # Activates the 'dev' profile, loads application-dev.yml if present

  servlet:
    multipart:
      max-file-size: 50MB  # Max size per uploaded file
      max-request-size: 100MB  # (optional) Total request size (all files + data)

springdoc:
  default-produces-media-type: application/json  # OpenAPI docs will use JSON by default

server:
  servlet:
    context-path: /api/v1/

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
